### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by ruudk** [lemonhall/esp32_dht11#1]
Hi,

I'm trying out this library on my ESP32 and every now and then I get `-2` (which is a `DHT_TIMEOUT_ERROR`)

```
Temperature reading 27
Temperature reading 27
Temperature reading -2
Temperature reading 27
Temperature reading -2
Temperature reading 27
Temperature reading -2
Temperature reading 27
Temperature reading 27
Temperature reading 27
```

What am I doing wrong?

**Comment by bitflip2** [comment]
I think the reason for this behaviour is the fact that there are a lot of modules called "DHT11" out on the market but their individual timings and return values can be quite different. Testing this with my "DHT11" and a logic analyzer pretty much confirmed this assumption. Therefore a lot of assumptions made by this library and its forks can be simply wrong for many modules.

An example would be this assignment and the following comparison :

https://github.com/lemonhall/esp32_dht11/blob/9382150a69e1f658feb63d8b197781e6124506b6/src/dht11.c#L169-L174

My device currently returns the following values:

``01000011 00000000 00011010 00000111 01100100``

which stands for 

relative humidity integral,   relative humidity decimal, temperature integral, temperature decimal, checksum

and in a human readable format:

´´67.0%  26.7°C´´

But the library does not consider the decimal part of the temperature, byte 4 ("bits[3]") in the creation of the checksum, so it pretty much always returns a "checksum error"
